apiVersion: apps/v1
kind: Deployment
metadata:
  name: springpet-deploy
  namespace: default
  labels:
    app: springpet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springpet
  template:
    metadata:
      labels:
        app: springpet
    spec:
      containers:
      - name: springpet
        image: docker.io/66816681/spring-app2   #custom image based on spring-petclinic 
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=MyJavaSpringSvc"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://opentelemetrycollector.default:4317"
---
apiVersion: v1
kind: Service
metadata:
  name: springpet-svc
  namespace: default
spec:
  selector:
    app: springpet
  ports:
    - targetPort: 8080
      port: 9090         
