apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
  labels:
    app: spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: docker.io/66816681/spring-app
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: spring-app-svc
spec:
  selector:
    app: spring-app
  ports:
    - targetPort: 80
      port: 80
