---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: default
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
      batch:
    exporters:
      logging:
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
        metrics:
          receivers: [otlp, logging]
          processors: [batch]
          exporters: [otlp, logging]
        logs:
          receivers: [otlp, logging]
          processors: [batch]
          exporters: [otlp, logging]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: default
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols: 
          grpc:
    processors:
      batch:
    exporters:
      otlp:
        endpoint: "opentelemetrycollector.default.svc.cluster.local:4317"
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
