---
apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: default
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      jaeger:
        protocols:
          grpc:
          thrift_http:
      zipkin: {}
    processors:
      batch:
      memory_limiter:
        # Same as --mem-ballast-size-mib CLI argument
        ballast_size_mib: 683
        # 80% of maximum memory up to 2G
        limit_mib: 1500
        # 25% of limit up to 2G
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
      zpages: {}
    exporters:
      logging:
        loglevel: info
      zipkin:
        endpoint: "http://somezipkin.target.com:9411/api/v2/spans" # Replace with a real endpoint.
      jaeger:
        endpoint: "somejaegergrpc.target.com:14250" # Replace with a real endpoint.
        insecure: true
    service:
      extensions: [health_check, zpages]
      pipelines:
        traces/1:
          receivers: [otlp, zipkin]
          processors: [memory_limiter, batch]
          exporters: [logging]
        traces/2:
          receivers: [otlp, jaeger]
          processors: [memory_limiter, batch]
          exporters: [logging]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: default
data:
  agent.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http::
    processors:
    exporters:
      otlp:
        endpoint: "opentelemetrycollector.default.svc.cluster.local:4317"
        insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp]

