apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
  namespace: default
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
