apiVersion: apps/v1
kind: Deployment
metadata:
  name: oteltestapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oteltestapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oteltestapp
    spec:
      containers:
      - name: oteltestapp
        image: quay.io/jpkroehling/generate-span-java:0.1.0
      - name: agent
        image: otel/opentelemetry-collector:0.18.0
        args:
        - --config=/conf/agent.yaml
        volumeMounts:
        - mountPath: /conf
          name: agent-config
      volumes:
      - configMap:
          items:
          - key: agent.yaml
            path: agent.yaml
          name: agent-config
        name: agent-config
